export enum ERROR {
  STUDENT_FIRST_NAME_IS_REQUIRED = 'STUDENT_FIRST_NAME_IS_REQUIRED',
  STUDENT_LAST_NAME_IS_REQUIRED = 'STUDENT_LAST_NAME_IS_REQUIRED',
  STUDENT_ENROLLMENT_DATE_IS_REQUIRED = 'STUDENT_ENROLLMENT_DATE_IS_REQUIRED',
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',
  COURSE_NAME_IS_REQUIRED = 'COURSE_NAME_IS_REQUIRED',
  COURSE_START_DATE_IS_REQUIRED = 'COURSE_START_DATE_IS_REQUIRED',
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  COURSE_UPDATE_PAYLOAD_EMPTY = 'COURSE_UPDATE_PAYLOAD_EMPTY',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'
}
