export enum ERROR {
  STUDENT_ID_MUST_BE_A_NUMBER = 'STUDENT_ID_MUST_BE_A_NUMBER',
  STUDENT_FIRST_NAME_IS_REQUIRED = 'STUDENT_FIRST_NAME_IS_REQUIRED',
  STUDENT_LAST_NAME_IS_REQUIRED = 'STUDENT_LAST_NAME_IS_REQUIRED',
  STUDENT_ENROLLMENT_DATE_IS_REQUIRED = 'STUDENT_ENROLLMENT_DATE_IS_REQUIRED',
  STUDENT_DOES_NOT_EXIST = 'STUDENT_DOES_NOT_EXIST'
}
